<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fathzer</groupId>
		<artifactId>parent-pom</artifactId>
		<version>1.1.0</version>
	</parent>
	<artifactId>javaluator-parent-pom</artifactId>
	<version>1.1.0</version>
	<packaging>pom</packaging>

	<name>javaluator-parent</name>
	<description>The parent pom used by javaluator.</description>
	<url>https://javaluator.fathzer.com</url>

	<scm>
		<url>https://github.com/fathzer/javaluator/tree/master/parent-pom</url>
		<connection>https://github.com/fathzer/javaluator.git</connection>
	</scm>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<animal-sniffer-signature>java18</animal-sniffer-signature>
	</properties>
	<profiles>
		<profile>
			<id>release</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<modules>
				<module>javaluator</module>
				<module>javaluator-examples</module>
			</modules>
		</profile>
		<profile>
			<id>demo</id>
			<properties>
				<maven.javadoc.skip>true</maven.javadoc.skip>
			</properties>
			<modules>
				<module>javaluator</module>
				<module>javaluator-demo</module>
			</modules>
		</profile>
	</profiles>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>animal-sniffer-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<executions>
					<execution>
						<id>default-compile</id>
						<configuration>
							<release>11</release>
							<!-- no excludes: compile everything to ensure
							module-info contains right entries -->
						</configuration>
					</execution>
					<execution>
						<id>base-compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<!-- recompile everything for target VM except the
							module-info.java -->
							<excludes>
								<exclude>module-info.java</exclude>
							</excludes>
						</configuration>
					</execution>
				</executions>
				<!-- defaults for compile and testCompile -->
				<configuration>
					<release>8</release>
					<!-- Requires Maven runtime JAVA_HOME is at least Java 9 or have configured the maven-toolchains-plugin -->
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>